version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    image: server
    ports:
      - "8000:8000"
    expose:
      - "8000"
